name: Build JIvpn
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: ğŸ› ï¸ REPARAR GRADLEW (Se faltar)
        run: |
          if [ ! -f gradlew ]; then
            echo "âš ï¸ Arquivo gradlew sumiu! Gerando um novo..."
            gradle wrapper --gradle-version 5.4.1
          fi
          chmod +x gradlew

      - name: ğŸš€ Build APK
        run: ./gradlew assembleRelease -x lint -x test --stacktrace
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JIvpn-Final
          path: app/build/outputs/apk/release/app-release.apk
