name: Build JIvpn
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup JDK 17 (Ferramentas)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup JDK 8 (Compilador)
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: ðŸ› ï¸ FIX GRADLE
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 5.4.1
          fi
          chmod +x gradlew
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=" >> local.properties 

      - name: ðŸš€ Build APK
        run: ./gradlew assembleRelease -x lint -x test --stacktrace
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }} 
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JIvpn-Final
          path: app/build/outputs/apk/release/app-release.apk
